server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  profiles:
    active: local
  threads:
    virtual:
      enabled: true
  datasource:
    primary:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ENC(JaLrajkeued2mbY9q+n+FN+0ZVV08tSYCNH3FBYmIrG5coNfty2pe2zrxDx+x741)
      username: ENC(uLTQ08k3Yxqe7xbMoAVknQ==)
      password: ENC(E+gwh1TBpsjWC/xYyfwP64W6grsvlnYS)
    replica:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ENC(BtXZinQCa/VY0Y7XFH9cTcWqy3ZS7g6pHz+4Yk9CD4olNJYN5d05Q9N8ujHoXm6x)
      username: ENC(ISqamVrX52GpJ5Ek4NhERA==)
      password: ENC(J/cPIpIJRqun07Yl1LQjqFfFD9Z2ZRXp)
  jooq:
    sql-dialect: postgres

logging:
  level:
    root: info
    org.springframework.boot.SpringApplication: info
    org.springframework.boot: error
    org.springframework.web: error
    org.springframework.security: error
    us.puter.park: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight([%5p]) [%thread] %cyan(%logger) - %msg%n"

jwt:
  secret: ENC(XXs167f7/pl/6Ad0xw6uebwq6vRl2vyKd1qcs3br0Ad+DRTnAwcE6SVufMpYzB98T6JEn7fbq/z+QRyDCvfl0HyHXaztXSa/QUWIc5/tk5W5ILJ7IYI9+Ykvh9qiijix1EQqMNl5Y6U0JSjOFCW3u3FDaI1OJupVE6Z+FpjNBX/Z0L0MEpmlCV8I7eLHajlU)
  access-token-valid-second: 7200
  refresh-token-valid-second: 86400

system:
  # AES256 암호화 키
  secret-key: ENC(gmmLJJ7tbFRFTiPMjZ2TenqmTyLhEnRHP4PPXPdEqETCrILe6aTPBnyjF1vSRp7L)
  # CORS Allowed Origin
  cors-allowed-origin: puter.us
  # Html title
  title: PUTER.US (테스트)
  # QR Code 크기 (단위: px)
  qr-code-size: 250
  shorten-uri:
    # shorten-uri 길이
    length: 6