server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    primary:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ENC(8wGb9LMLjcNRbEO/orRAsoLXnBOJbCU4abr0avdram0PvbI8g3GG+m+1tdXeKS0AUlIp0cDyAV4=)
      username: ENC(XsgP44rqBcQvEvnmx9V/lg==)
      password: ENC(bSa8H1gg8+Mkyk4rJ1c1U2co8THaVmp9)
    replica:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ENC(hInTQiWZUDK4rjxHMyFWoMxYViUm5JbbWh09qHRPPRMzyR5FXoyXN/kbOo0DXRuGhg08+QIK1kg=)
      username: ENC(YkgrUptZqmzxGsFhVVZyZw==)
      password: ENC(+89rFMkeSB9MBzEbE7r7LZrJhA7kqefI)
  jooq:
    sql-dialect: postgres
  data:
    redis:
      host: ENC(qr2i7knTIjsdwLMaoIKZZcy1NaVUhqIR5wzB0W7BMBY3U2dPRON8kuCRz1Dad44LqFdozVG6Zh8Ad9CfiIc81/nvD6Wp0sco)
      port: 10212
      password: ENC(DmSpNvK0fA4JSAMvshb+zCcWuul4wjjEAgvBGJ/yixTYZ/PfehAaAjfTvxAdhrS5)

logging:
  level:
    root: info
    org.springframework.boot.SpringApplication: info
    org.springframework.boot: error
    org.springframework.web: error
    org.springframework.security: error
    org.jooq.tools.LoggerListener: debug
    us.puter.park: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight([%5p]) [%thread] %cyan(%logger) - %msg%n"

jwt:
  secret: ENC(8NwMZEK1MSk24GHpw5y5GgP62/9K3iYxLikCuyF2OCYTLbMsloyRyK8vglwYd7ObIWh7S9bAfEZIdLG0fL2lNTKGFirdjnucSNzUXoVn8oaJzJbrjMHMhVlhGJN/TKB+uZplh+IgUaXb5MEixUU9hQkH2Kc021JWURCSjM410mrEf4jQZ0oscSRY9oKBXExq)
  access-token-valid-second: 7200
  refresh-token-valid-second: 86400

system:
  # AES256 암호화 키
  secret-key: ENC(/2xrpptxpWZ55cVv6Wtv9OoVQrpqOIkoSkomSgY8ji0UpKC/e74SYLXT6lXj4e5E)
  # CORS Allowed Origin
  cors-allowed-origin: puter.us,tool.puter.us
  # Html title
  title: PUTER.US (dev)
  # QR Code 크기 (단위: px)
  qr-code-size: 250
  shorten-uri:
    # shorten-uri 길이
    length: 6