server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    primary:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ENC(noZ/xZnGuK7I65SwCTMFXrXnRIknGIkDCxhijY0RA0ePXBcHLuhaNC9v5G4wDgGxjCI3Kve6Nvg=)
      username: ENC(uLTQ08k3Yxqe7xbMoAVknQ==)
      password: ENC(E+gwh1TBpsjWC/xYyfwP64W6grsvlnYS)
    replica:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ENC(KmnJAbclNDKZ0XredU+bel3o6rH7jC6amuqdHfaAaIEJDNFBCUkCA9J00TlVu/QT2+ThFrZN4WE=)
      username: ENC(ISqamVrX52GpJ5Ek4NhERA==)
      password: ENC(J/cPIpIJRqun07Yl1LQjqFfFD9Z2ZRXp)
  jooq:
    sql-dialect: postgres
  data:
    redis:
      host: ENC(U9m4XWUhwe7cRnCHvUgSynXo2qUsqups)
      port: 16379
      password: ENC(cMFl4l7Fo9O3sVw5ehclANHcf4jlPxbq)

logging:
  level:
    root: info
    org.springframework.boot.SpringApplication: info
    org.springframework.boot: error
    org.springframework.web: error
    org.springframework.security: error
    org.jooq.tools.LoggerListener: debug
    us.puter.park: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight([%5p]) [%thread] %cyan(%logger) - %msg%n"

jwt:
  secret: ENC(XXs167f7/pl/6Ad0xw6uebwq6vRl2vyKd1qcs3br0Ad+DRTnAwcE6SVufMpYzB98T6JEn7fbq/z+QRyDCvfl0HyHXaztXSa/QUWIc5/tk5W5ILJ7IYI9+Ykvh9qiijix1EQqMNl5Y6U0JSjOFCW3u3FDaI1OJupVE6Z+FpjNBX/Z0L0MEpmlCV8I7eLHajlU)
  access-token-valid-second: 7200
  refresh-token-valid-second: 86400

system:
  # AES256 암호화 키
  secret-key: ENC(gmmLJJ7tbFRFTiPMjZ2TenqmTyLhEnRHP4PPXPdEqETCrILe6aTPBnyjF1vSRp7L)
  # CORS Allowed Origin
  cors-allowed-origin: puter.us,tool.puter.us
  # Html title
  title: PUTER.US (dev)
  # QR Code 크기 (단위: px)
  qr-code-size: 250
  shorten-uri:
    # shorten-uri 길이
    length: 6